### PR TITLE
Porting over changes from rethinkdb helm chart.

### PR DESCRIPTION
**Pull request by meenie**
- The path to the probe has changed from `/probe` to `/rethinkdb-probe`.
- Add RETHINKDB_PASSWORD environment variable to set `--initial-password`.
- Remove `ready-probe.sh` because I don't think it's being used.
- A bit of re-organizing of the files.
- Update version of Docker Tag to 2.3.5-v2.

### CODE REVIEW

**Comment by toredash** [comment]
I think we should keep the ready-probe.sh but maybe look at another way of testing it. Suggestion: compile a python binary that will connect to localhost,
and query system table.

Something like this:
```
import rethinkdb as r
r.connect('localhost', 28015).repl()
list(r.db('rethinkdb').table('server_status').run())
```

Then we at least know when it is ready to receive queries.

What do you think ?

**Comment by meenie** [comment]
@toredash: There is still a probe located under the `rethinkdb-probe` folder.  When `make` is run, one of the things it does is build the probe and add it to the finished Docker image.  The `ready-probe.sh` file I removed seemed to be extra and not needed.  Unless I misunderstand the need for it?

**Comment by toredash** [comment]
@meenie You are right, I was under the impression that the probe(.go) file was removed in this PR. My bad :)

**Comment by meenie** [comment]
@rosskukulinski Friendly bump :)

**Comment by rosskukulinski** [comment]
@meenie holy smokes! How did I miss this?  Thank you - I'll look this week :)

**Comment by meenie** [comment]
All good! No hurry, my PR into the Helm Charts repo doesn't really need this to get merged. Just will be nice to clean up the codebase in the future. Have a great day!

**Comment by meenie** [comment]
@rosskukulinski Friendly bump on this :). I'm making some updates to the helm chart I created for rethink and if this could get merged I can update it to use your image instead of mine.

**Comment by rafi** [comment]
rethinkdb 2.4.0 is out

**Pull request closed without merging**
